// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVApXK7Sn6NGCx1STImuHtKU3e_3nf2k',
    appId: '1:896621147541:web:ff7238062e78c9e915729c',
    messagingSenderId: '896621147541',
    projectId: 'doancuoiki-fbffe',
    authDomain: 'doancuoiki-fbffe.firebaseapp.com',
    storageBucket: 'doancuoiki-fbffe.firebasestorage.app',
    measurementId: 'G-R4N2HBHH86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKaJ5RGrH2AcfiY7swl7q25Map7Ab83bI',
    appId: '1:896621147541:android:c6f2a5506d541a1d15729c',
    messagingSenderId: '896621147541',
    projectId: 'doancuoiki-fbffe',
    storageBucket: 'doancuoiki-fbffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwRD8VM1r5Bl5fIiA_ub6C4pHx1TAsslg',
    appId: '1:896621147541:ios:08003fdbcd9c9b5415729c',
    messagingSenderId: '896621147541',
    projectId: 'doancuoiki-fbffe',
    storageBucket: 'doancuoiki-fbffe.firebasestorage.app',
    iosBundleId: 'com.example.doancuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwRD8VM1r5Bl5fIiA_ub6C4pHx1TAsslg',
    appId: '1:896621147541:ios:08003fdbcd9c9b5415729c',
    messagingSenderId: '896621147541',
    projectId: 'doancuoiki-fbffe',
    storageBucket: 'doancuoiki-fbffe.firebasestorage.app',
    iosBundleId: 'com.example.doancuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVApXK7Sn6NGCx1STImuHtKU3e_3nf2k',
    appId: '1:896621147541:web:f03df60fe7db4e5a15729c',
    messagingSenderId: '896621147541',
    projectId: 'doancuoiki-fbffe',
    authDomain: 'doancuoiki-fbffe.firebaseapp.com',
    storageBucket: 'doancuoiki-fbffe.firebasestorage.com',
    measurementId: 'G-EH6FCV463T',
  );
}
